model:
  name: "ahmedheakl/gg-armv8-O0"
  architecture: "qwen"
  max_length: 15500 #Note: this is ignored in qwen models
  num_beams: 1
  num_return_sequences: 1
  temperature: 0.7
  k: 5

dataset:
  name: "adpretko/reducedeval"
  split: "train"
  skip_files:
    [
      "problem999"
    ]
  source_lang: "x86"
  target_lang: "arm"