run:
  name: "qwen2.5_1.5b_run_on_project_euler_arm64_to_riscv"
  timestamp: null 
  save_artifacts_path: "artifacts/"
  
# Model Configuration
model:
  name: "ahmedheakl/qwen2.5_1.5b_500k_16kcw_2ep_armv8"
  is_enc_dec: false
  checkpoint: "..." 
  max_length: 1000

# Inference Configuration
inference:
  beam_size: 50
  temperature: 0.7
  k: 20
  num_guesses: 50
  lambda_val: 0.95

# Language Configuration
language:
  source_lang: "arm64"
  target_lang: "riscv"
  viceversa: false

# Data Configuration
dataset:
  name: "project_euler"
  gcc_args: "..."
  additional_notes: "Project Euler problems translated from ARM64 to RISC-V"

# Feature Flags
features:
  guess: false
  sketch: false
  few_shot: false
  verbose: false
  log_attention_maps: true

# Sketch Configuration
sketch:
  template_path: "scratch_sketch.rkt"
  view_uncertain: ""
