# Launch specification for Qwen model on BringUp dataset (ARM to RISC-V)

model:
  name: qwen
  checkpoint: Qwen/Qwen1.5-7B-Chat
  revision: main
  tokenizer:
    name: Qwen/Qwen1.5-7B-Chat
    revision: main
  generation_params:
    temperature: 0.2
    top_p: 0.95
    max_new_tokens: 4096

dataset:
  name: bringup
  path: data/datasets/BringUp
  source_arch: arm
  target_arch: risc

prompt_template: |
  You are an expert in assembly language and computer architecture. Your task is to translate the following assembly code from ARM architecture to RISC-V architecture.
  
  ARM assembly code:
  ```arm
  {{source}}
  ```
  
  Please translate the above ARM assembly code to equivalent RISC-V assembly code. Preserve the functionality and structure as much as possible.
  
  RISC-V assembly code:
  ```risc-v

response_template: |
  {{response}}
  ```

output_dir: results/bringup_arm2risc
