run:
  name: "bartlarge_risctoarm_cloze2048_run_on_humaneval_RISC5_to_ARM64"
  timestamp: null
  save_artifacts_path: "artifacts/"

# Model Configuration
model:
  name: "celinelee/bartlarge_risctoarm_cloze2048"
  is_enc_dec: true
  checkpoint: "..."
  max_length: 2048

# Inference Configuration
inference:
  beam_size: 1
  temperature: 0.7
  num_guesses: 1
  lambda_val: 0.95

# Language Configuration
language:
  source_lang: "riscv"
  target_lang: "arm64"
  viceversa: false

# Data Configuration
dataset:
  name: "unix_commands"
  gcc_args: "..."
  additional_notes: "..."

# Sketch Configuration
sketch:
  template_path: "scratch_sketch.rkt"
  view_uncertain: ""
