run:
  name: "bartlarge_risctoarm_cloze2048_run_on_humaneval_RISC5_to_ARM64"
  timestamp: null 
  save_artifacts_path: "artifacts/"
  
# Model Configuration
model:
  name: "celinelee/bartlarge_risctoarm_cloze2048"
  is_enc_dec: true
  checkpoint: "..." 
  max_length: 2048

# Inference Configuration
inference:
  beam_size: 5
  temperature: 0.7
  k: 20
  num_guesses: 50
  lambda_val: 0.95

# Language Configuration
language:
  source_lang: "RISC5"
  target_lang: "ARM64"
  viceversa: false

# Data Configuration
dataset:
  name: "human-eval"
  gcc_args: "..."
  additional_notes: "..."

# Feature Flags
features:
  guess: false
  sketch: false
  few_shot: false
  verbose: false
  log_attention_maps: true

# Sketch Configuration
sketch:
  template_path: "scratch_sketch.rkt"
  view_uncertain: ""