dataset:
  additional_notes: '...'
  gcc_args: '...'
  name: unix_commands
features:
  few_shot: false
  guess: false
  log_attention_maps: true
  sketch: false
  verbose: false
inference:
  beam_size: 5
  k: 20
  lambda_val: 0.95
  num_guesses: 50
  temperature: 0.7
language:
  source_lang: x86
  target_lang: arm64
  viceversa: false
model:
  checkpoint: '...'
  is_enc_dec: false
  max_length: 1024
  name: ahmedheakl/qwen2.5_1.5b_1M_stack_16kcw_2ep
run:
  name: qwen2.5_1.5b_run_on_humaneval_x86_to_arm64
  save_artifacts_path: artifacts/ahmedheakl/qwen2.5_1.5b_1M_stack_16kcw_2ep/20250325_163507
  timestamp: '20250325_163507'
sketch:
  template_path: scratch_sketch.rkt
  view_uncertain: ''
